{
  "name": "angular-electron",
  "version": "14.0.1",
  "description": "Angular 17 with Electron 30 (Typescript + SASS + Hot Reload)",
  "homepage": "https://github.com/maximegris/angular-electron",
  "author": {
    "name": "Maxime GRIS",
    "email": "maxime.gris@gmail.com"
  },
  "keywords": [
    "angular",
    "angular 17",
    "electron",
    "electron 30",
    "nodejs",
    "typescript",
    "jest",
    "playwright",
    "eslint",
    "sass",
    "windows",
    "mac",
    "linux"
  ],
  "main": "app/main.js",
  "private": true,
  "scripts": {
    "postinstall": "electron-builder install-app-deps",
    "ng": "ng",
    "s": "ng s",
    "start": "npm-run-all -p electron:serve ng:serve",
    "ng:serve": "ng serve -c web -o",
    "build": "npm run electron:serve-tsc && ng build --base-href ./",
    "build:dev": "npm run build -- -c dev",
    "build:prod": "npm run build -- -c production",
    "web:build": "npm run build -- -c web-production",
    "electron": "electron",
    "electron:serve-tsc": "tsc -p tsconfig.serve.json",
    "electron:serve": "wait-on tcp:4200 && npm run electron:serve-tsc && electron . --serve",
    "electron:local": "npm run build:prod && electron .",
    "electron:build": "npm run build:prod && electron-builder build --publish=never",
    "test": "ng test --watch=false",
    "test:watch": "ng test",
    "e2e": "npm run build:prod && playwright test -c e2e/playwright.config.ts e2e/",
    "e2e:show-trace": "playwright show-trace e2e/tracing/trace.zip",
    "version": "conventional-changelog -i CHANGELOG.md -s -r 0 && git add CHANGELOG.md",
    "lint": "ng lint"
  },
  "dependencies": {
    "@angular/animations": "^18.2.0",
    "@angular/common": "^18.2.0",
    "@angular/compiler": "^18.2.0",
    "@angular/core": "^18.2.0",
    "@angular/forms": "^18.2.0",
    "@angular/platform-browser": "^18.2.0",
    "@angular/platform-browser-dynamic": "^18.2.0",
    "@angular/router": "^18.2.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.10"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^18.2.10",
    "@angular/cli": "^18.2.10",
    "@angular/compiler-cli": "^18.2.0",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.2.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.5.2",
    "@angular-builders/custom-webpack": "~18.0.0",
    "@angular-builders/jest": "~18.0.0",
    "@angular-eslint/builder": "~18.0.0",
    "@angular-eslint/eslint-plugin": "~18.0.0",
    "@angular-eslint/eslint-plugin-template": "~18.0.0",
    "@angular-eslint/schematics": "~18.0.0",
    "@angular-eslint/template-parser": "~18.0.0",
    "@ngx-translate/core": "15.0.0",
    "@ngx-translate/http-loader": "8.0.0",
    "@playwright/test": "1.43.1",
    "@types/jest": "29.5.12",
    "@types/node": "20.12.7",
    "@typescript-eslint/eslint-plugin": "7.7.1",
    "@typescript-eslint/parser": "7.7.1",
    "conventional-changelog-cli": "4.1.0",
    "electron": "30.0.1",
    "electron-builder": "24.13.3",
    "electron-debug": "3.2.0",
    "electron-reloader": "1.2.3",
    "eslint": "8.57.0",
    "eslint-plugin-import": "2.29.1",
    "eslint-plugin-jsdoc": "48.2.3",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "jest": "29.7.0",
    "node-polyfill-webpack-plugin": "2.0.1",
    "npm-run-all": "4.1.5",
    "playwright": "1.43.1",
    "ts-node": "10.9.2",
    "wait-on": "7.2.0",
    "webdriver-manager": "12.1.9"
  },
  "engines": {
    "node": ">= 16.14.0 || >= 18.10.0"
  },
  "browserslist": [
    "chrome 114"
  ]
}
